{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/firebaseinappmessaging"]},{"paths":["\/documentation\/firebaseinappmessaging"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Framework","externalID":"FirebaseInAppMessaging","role":"collection","symbolKind":"module","modules":[{"name":"FirebaseInAppMessaging"}],"title":"FirebaseInAppMessaging"},"kind":"symbol","sections":[],"hierarchy":{"paths":[[]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessaging","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingAction","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingActionButton","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingBannerDisplay","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingCampaignInfo","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingCardDisplay","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingDisplayMessage","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingImageData","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingImageOnlyDisplay","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingModalDisplay"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingDisplay","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingDisplayDelegate"]},{"identifiers":["doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIAMDisplayRenderErrorType","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIRInAppMessagingDismissType","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIRInAppMessagingDisplayMessageType","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIRInAppMessagingDisplayTriggerType","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingPreviewHelpers"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/SwiftUI"]}],"references":{"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingModalDisplay":{"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingModalDisplay","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"InAppMessagingModalDisplay","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InAppMessagingModalDisplay"}],"url":"\/documentation\/firebaseinappmessaging\/inappmessagingmodaldisplay","title":"InAppMessagingModalDisplay"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessaging":{"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessaging","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InAppMessaging"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InAppMessaging"}],"url":"\/documentation\/firebaseinappmessaging\/inappmessaging","title":"InAppMessaging"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingCardDisplay":{"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingCardDisplay","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"InAppMessagingCardDisplay","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InAppMessagingCardDisplay"}],"url":"\/documentation\/firebaseinappmessaging\/inappmessagingcarddisplay","title":"InAppMessagingCardDisplay"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/SwiftUI":{"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/SwiftUI","kind":"symbol","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/firebaseinappmessaging\/swiftui","title":"SwiftUI"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingImageData":{"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingImageData","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InAppMessagingImageData"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InAppMessagingImageData"}],"url":"\/documentation\/firebaseinappmessaging\/inappmessagingimagedata","title":"InAppMessagingImageData"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingDisplay":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"InAppMessagingDisplay","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"InAppMessagingDisplay"}],"title":"InAppMessagingDisplay","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingDisplay","url":"\/documentation\/firebaseinappmessaging\/inappmessagingdisplay","abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/FirebaseInAppMessagingVersionString":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"FirebaseInAppMessagingVersionString"}],"title":"FirebaseInAppMessagingVersionString","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FirebaseInAppMessagingVersionString","url":"\/documentation\/firebaseinappmessaging\/firebaseinappmessagingversionstring","abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingActionButton":{"role":"symbol","title":"InAppMessagingActionButton","navigatorTitle":[{"text":"InAppMessagingActionButton","kind":"identifier"}],"url":"\/documentation\/firebaseinappmessaging\/inappmessagingactionbutton","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingActionButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"InAppMessagingActionButton","kind":"identifier"}]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/FirebaseInAppMessagingVersionNumber":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"FirebaseInAppMessagingVersionNumber"}],"title":"FirebaseInAppMessagingVersionNumber","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FirebaseInAppMessagingVersionNumber","url":"\/documentation\/firebaseinappmessaging\/firebaseinappmessagingversionnumber","abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging":{"url":"\/documentation\/firebaseinappmessaging","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging","title":"FirebaseInAppMessaging","abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingAction":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InAppMessagingAction"}],"navigatorTitle":[{"kind":"identifier","text":"InAppMessagingAction"}],"title":"InAppMessagingAction","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingAction","url":"\/documentation\/firebaseinappmessaging\/inappmessagingaction","abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/FIRInAppMessagingDisplayTriggerType":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FIRInAppMessagingDisplayTriggerType"}],"navigatorTitle":[{"text":"FIRInAppMessagingDisplayTriggerType","kind":"identifier"}],"role":"symbol","title":"FIRInAppMessagingDisplayTriggerType","url":"\/documentation\/firebaseinappmessaging\/firinappmessagingdisplaytriggertype","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIRInAppMessagingDisplayTriggerType","kind":"symbol"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/FIRInAppMessagingDisplayMessageType":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FIRInAppMessagingDisplayMessageType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FIRInAppMessagingDisplayMessageType"}],"title":"FIRInAppMessagingDisplayMessageType","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIRInAppMessagingDisplayMessageType","url":"\/documentation\/firebaseinappmessaging\/firinappmessagingdisplaymessagetype","abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingPreviewHelpers":{"type":"topic","title":"InAppMessagingPreviewHelpers","url":"\/documentation\/firebaseinappmessaging\/inappmessagingpreviewhelpers","navigatorTitle":[{"text":"InAppMessagingPreviewHelpers","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingPreviewHelpers","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessagingPreviewHelpers","kind":"identifier"}]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingImageOnlyDisplay":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InAppMessagingImageOnlyDisplay"}],"navigatorTitle":[{"kind":"identifier","text":"InAppMessagingImageOnlyDisplay"}],"title":"InAppMessagingImageOnlyDisplay","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingImageOnlyDisplay","url":"\/documentation\/firebaseinappmessaging\/inappmessagingimageonlydisplay","abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/FIRInAppMessagingDismissType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FIRInAppMessagingDismissType","kind":"identifier"}],"abstract":[],"url":"\/documentation\/firebaseinappmessaging\/firinappmessagingdismisstype","role":"symbol","navigatorTitle":[{"text":"FIRInAppMessagingDismissType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIRInAppMessagingDismissType","type":"topic","kind":"symbol","title":"FIRInAppMessagingDismissType"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingCampaignInfo":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessagingCampaignInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/firebaseinappmessaging\/inappmessagingcampaigninfo","role":"symbol","navigatorTitle":[{"text":"InAppMessagingCampaignInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingCampaignInfo","type":"topic","kind":"symbol","title":"InAppMessagingCampaignInfo"},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingDisplayDelegate":{"url":"\/documentation\/firebaseinappmessaging\/inappmessagingdisplaydelegate","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"InAppMessagingDisplayDelegate","kind":"identifier"}],"title":"InAppMessagingDisplayDelegate","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingDisplayDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessagingDisplayDelegate","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingDisplayMessage":{"role":"symbol","title":"InAppMessagingDisplayMessage","navigatorTitle":[{"text":"InAppMessagingDisplayMessage","kind":"identifier"}],"url":"\/documentation\/firebaseinappmessaging\/inappmessagingdisplaymessage","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingDisplayMessage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"InAppMessagingDisplayMessage","kind":"identifier"}]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/FIAMDisplayRenderErrorType":{"navigatorTitle":[{"text":"FIAMDisplayRenderErrorType","kind":"identifier"}],"url":"\/documentation\/firebaseinappmessaging\/fiamdisplayrendererrortype","title":"FIAMDisplayRenderErrorType","role":"symbol","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FIAMDisplayRenderErrorType","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FIAMDisplayRenderErrorType","kind":"identifier"}]},"doc://org.cocoapods.FirebaseInAppMessaging/documentation/FirebaseInAppMessaging/InAppMessagingBannerDisplay":{"title":"InAppMessagingBannerDisplay","identifier":"doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/InAppMessagingBannerDisplay","navigatorTitle":[{"text":"InAppMessagingBannerDisplay","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"InAppMessagingBannerDisplay","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/firebaseinappmessaging\/inappmessagingbannerdisplay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FirebaseInAppMessagingVersionNumber","doc:\/\/org.cocoapods.FirebaseInAppMessaging\/documentation\/FirebaseInAppMessaging\/FirebaseInAppMessagingVersionString"],"title":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}